
test.py:data_loader() 보니까 --dropout_rate은 적용 안 되는 듯함. --> 5th_trial
4th_trial의 model 폴더: "models_data_04"로 변경
"""#################################################################################"""
==> change default parameters in """model.py:Line74"""
    def __init(self, base_model, fixed_weight=False, dropout_rate=0.5, bayesian=False):

Re-training...(Not yet)
$ python3 train.py --image_path ./data --metadata_path ./data/dataset_train.txt --num_epochs 50 --model_save_step 25

$ tensorboard --logdir ./summary_data

$ python3 test.py --image_path ./data --metadata_path ./data/dataset_test.txt
# 여전히 overall error가 너무 큼
model.py:Line74, 75 원상복구(default dropout_rate)